/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionSlugRouteImport } from './routes/region.$slug'
import { Route as CountryCodeRouteImport } from './routes/country.$code'
import { Route as CompareABRouteImport } from './routes/compare.$a.$b'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionSlugRoute = RegionSlugRouteImport.update({
  id: '/region/$slug',
  path: '/region/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/country/$code',
  path: '/country/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareABRoute = CompareABRouteImport.update({
  id: '/compare/$a/$b',
  path: '/compare/$a/$b',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/sources': typeof SourcesRoute
  '/country/$code': typeof CountryCodeRoute
  '/region/$slug': typeof RegionSlugRoute
  '/compare/$a/$b': typeof CompareABRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/sources': typeof SourcesRoute
  '/country/$code': typeof CountryCodeRoute
  '/region/$slug': typeof RegionSlugRoute
  '/compare/$a/$b': typeof CompareABRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/glossary': typeof GlossaryRoute
  '/sources': typeof SourcesRoute
  '/country/$code': typeof CountryCodeRoute
  '/region/$slug': typeof RegionSlugRoute
  '/compare/$a/$b': typeof CompareABRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/glossary'
    | '/sources'
    | '/country/$code'
    | '/region/$slug'
    | '/compare/$a/$b'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/glossary'
    | '/sources'
    | '/country/$code'
    | '/region/$slug'
    | '/compare/$a/$b'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/glossary'
    | '/sources'
    | '/country/$code'
    | '/region/$slug'
    | '/compare/$a/$b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GlossaryRoute: typeof GlossaryRoute
  SourcesRoute: typeof SourcesRoute
  CountryCodeRoute: typeof CountryCodeRoute
  RegionSlugRoute: typeof RegionSlugRoute
  CompareABRoute: typeof CompareABRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/$slug': {
      id: '/region/$slug'
      path: '/region/$slug'
      fullPath: '/region/$slug'
      preLoaderRoute: typeof RegionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$code': {
      id: '/country/$code'
      path: '/country/$code'
      fullPath: '/country/$code'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$a/$b': {
      id: '/compare/$a/$b'
      path: '/compare/$a/$b'
      fullPath: '/compare/$a/$b'
      preLoaderRoute: typeof CompareABRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GlossaryRoute: GlossaryRoute,
  SourcesRoute: SourcesRoute,
  CountryCodeRoute: CountryCodeRoute,
  RegionSlugRoute: RegionSlugRoute,
  CompareABRoute: CompareABRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
