/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeRouteImport } from './routes/country.$code'
import { Route as CompareABRouteImport } from './routes/compare.$a.$b'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/country/$code',
  path: '/country/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareABRoute = CompareABRouteImport.update({
  id: '/compare/$a/$b',
  path: '/compare/$a/$b',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/country/$code': typeof CountryCodeRoute
  '/compare/$a/$b': typeof CompareABRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/country/$code': typeof CountryCodeRoute
  '/compare/$a/$b': typeof CompareABRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/country/$code': typeof CountryCodeRoute
  '/compare/$a/$b': typeof CompareABRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/country/$code' | '/compare/$a/$b'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/country/$code' | '/compare/$a/$b'
  id: '__root__' | '/' | '/country/$code' | '/compare/$a/$b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryCodeRoute: typeof CountryCodeRoute
  CompareABRoute: typeof CompareABRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$code': {
      id: '/country/$code'
      path: '/country/$code'
      fullPath: '/country/$code'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$a/$b': {
      id: '/compare/$a/$b'
      path: '/compare/$a/$b'
      fullPath: '/compare/$a/$b'
      preLoaderRoute: typeof CompareABRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryCodeRoute: CountryCodeRoute,
  CompareABRoute: CompareABRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
